### ISSUE TITLE
[Query] thresholds and time sequencing in read query #8

### ISSUE THREAD

**Issue by tian-zhong** [ldbc/ldbc_finbench_docs#12]
1. The threshold for edge1 (transfer) and the threshold for edge2 ( withdraw ) should not be the same.
2. The timing of transfer and withdrawal is not significant as long as they are within the range of the inquiry time window.

**Comment by qishipengqsp** [comment]
Have talked with @tian-zhong , such a time sequencing design exists in some scenarios like finding exact transfer traces. We need to reconsider the query cases in transaction workload if they aim to find transfer traces. If not, we may need to add more queries that can be representative.
