### ISSUE TITLE
[Format] Doc has some format or type errors.

### ISSUE THREAD

**Issue by zhengJade** [ldbc/ldbc_finbench_docs#41]
**Complex-read3**  has a format error in params.
![image](https://user-images.githubusercontent.com/30115816/209521711-d812fe58-858a-49e3-a176-fd5d53f58608.png)
Please remove the special symbol.

**Complex-read8** word ratio's font is different from other words.
![image](https://user-images.githubusercontent.com/30115816/209621327-c2a21be0-4969-431e-be74-5d85f804b82c.png)
**Complex-read9**
![image](https://user-images.githubusercontent.com/30115816/209644812-ed3cf7a2-be9c-4d63-b14a-1418367a5001.png)
Result could't match query result description.

**Complex-read12**
![image](https://user-images.githubusercontent.com/30115816/209670717-ee1cfe0b-dd2f-4a5c-b73f-d0ca5509e3da.png)
Pattern description can't match result.

**Comment by qishipengqsp** [comment]
miss 'ratio' property in 'invest' edge.
