### ISSUE TITLE
Complex-Read Query Have Some Question

### ISSUE THREAD

**Issue by BingTong0** [ldbc/ldbc_finbench_docs#45]
Complex-read 4
result: add otherAccount
![image](https://user-images.githubusercontent.com/111406211/210358926-bd389366-0074-4040-a68c-e3f3dad5153a.png)

Complex-read 5
question: 
1.If it have a path a->b->c->d, whether we need output a->b->c?
2.If it have a path a->b->c->b->d, is the path right?

Complex-read 6
result: add mid
![image](https://user-images.githubusercontent.com/111406211/210359058-94c4d34f-4227-48ae-9b18-d422675c4621.png)

Complex-read 7
question: If count(e2)==0, how to output result? 
![image](https://user-images.githubusercontent.com/111406211/210359143-9673c1ed-5f71-4391-8b25-b649efc406dd.png)

Complex-read 8
question: There maybe have many ratio1/ratio2/ratio3, how to distinguish it?

Complex-read 9
params: add id
question: I think there will have many pair of edge1 and edge2, how to choose it?

Complex-read 10
params: add start_time, end_time, truncation_limit, truncation_order

Complex-read 11
question: I didn't understand how to calculate `final share`.

Complex-read 12
title: Cycle -> Chain?
params: add start_time, end_time, truncation_limit, truncation_order
result: add `Loan`
pattern: 
1.Do we want to consider the time of apply relationship?
2.How do we deal end if it find a cycle in the chain? .e.g，p1->p2->p3->p4->p2.
![image](https://user-images.githubusercontent.com/111406211/210334344-a2c793c4-d4e1-4d34-b405-b29df7c55ce5.png)

Complex-read 13
result: add `Company`
![image](https://user-images.githubusercontent.com/111406211/210333410-9f0332bf-4580-4f51-be09-a4b3ad5d77ba.png)

**Comment by BingTong0** [comment]
Complex-read 7
The order of the params is as follows to be more consistent with other queries
1. id
2. threshold
3. start_time
4. end_time
5. truncation_limit
6. truncation_order

**Comment by qishipengqsp** [comment]
- CR 4: It's a problem in describing `groupby`. Will fix in #50 
- CR 5: Discussed.
- CR 6: It's a problem in describing `groupby`. Will fix in #50 
- CR 7: Fixed
- CR 8: It's a problem in describing `groupby`. Will fix in #50 
- CR 9: Do aggregation. Already noted it as sum calculation.
- CR 10: No truncation here.
- CR 11: Discussed.
- CR 12: The timestamp of Loan apply should not be considered. Guarantee cycle is meanless data in reality.
- CR 13: It's a problem in describing `groupby`. Will fix in #50
