### ISSUE TITLE
put funcation result as a name

### ISSUE THREAD

**Issue by BingTong0** [ldbc/ldbc_finbench_docs#46]
.e.g Complex-read12
result: SUM(loan.loanAmount) -> sumLoanAmount

**Comment by qishipengqsp** [comment]
And re-check the results from divided list to tuples

**Comment by qishipengqsp** [comment]
> And re-check the results from divided list to tuples

Leave it to solve in the alpha test
https://github.com/ldbc/ldbc_finbench_docs/issues/50
