### ISSUE TITLE
simple-read and write query have some question

### ISSUE THREAD

**Issue by BingTong0** [ldbc/ldbc_finbench_docs#49]
SimpleRead1

result: properties id todo

SimpleRead3

result: The result does not require a set, .e. g accounts.id([ID]) ->  accountId(ID)

SimpleRead4

params: add startTime,endTime

SimpleRead6

result: The result does not require a set, .e. g companies.id([ID]) ->  companyId(ID)

SimpleRead7

result: The result does not require a set, .e. g COLLECT(DISTINCT dstAccount.id)([ID]) ->  dstAccountId(ID)

write3

params: add srcId,dstId

params: amount64-bit Integer has format problem

write5

params: add currentTime

write6

params: add currentTime

write8

params: amt -> amount, Complete spelling will be more consistent with other queries

write9

params: amt -> amount, Complete spelling will be more consistent with other queries

write11:

params: accountId -> mediumId

write12:

params: 

1. personId1
2. personId2
3. currentTime

write14:

pattern:it also have apply edge

**Comment by qishipengqsp** [comment]
> SimpleRead1
> 
> result: properties id todo
>
Done 
> SimpleRead3
> 
> result: The result does not require a set, .e. g accounts.id([ID]) -> accountId(ID)
> 
It does require. A company may have more than one accounts, loan, etc..
> SimpleRead4
> 
> params: add startTime,endTime
> 
Done
> SimpleRead6
> 
> result: The result does not require a set, .e. g companies.id([ID]) -> companyId(ID)
> 
It does require.
> SimpleRead7
> 
> result: The result does not require a set, .e. g COLLECT(DISTINCT dstAccount.id)([ID]) -> dstAccountId(ID)
> 
It does require.
> write3
> 
> params: add srcId,dstId
> 
> params: amount64-bit Integer has format problem
> 
Done
> write5
> 
> params: add currentTime
> 
Done
> write6
> 
> params: add currentTime
> 
Done
> write8
> 
> params: amt -> amount, Complete spelling will be more consistent with other queries
> 
Done
> write9
> 
> params: amt -> amount, Complete spelling will be more consistent with other queries
> 
Done
> write11:
> 
> params: accountId -> mediumId
> 
Done
> write12:
> 
> params:
> 
> 1. personId1
> 2. personId2
> 3. currentTime
> 
Done
> write14:
> 
> pattern:it also have apply edge
Done
