### ISSUE TITLE
Simple read have some question

### ISSUE THREAD

**Issue by BingTong0** [ldbc/ldbc_finbench_docs#52]
In the implementation phase:

simple read 4
result: there need have two results about `numEdges` & `sumAmount`

simple read 5
result: desc have a result about `the transfer amount per day`

**Comment by qishipengqsp** [comment]
> In the implementation phase:
> 
> simple read 4 result: there need have two results about `numEdges` & `sumAmount`
>
 
- Will fix it
> simple read 5 result: desc have a result about `the transfer amount per day`

- Will delete this result.
