### ISSUE TITLE
Complex read have some question

### ISSUE THREAD

**Issue by BingTong0** [ldbc/ldbc_finbench_docs#53]
In the implementation phase:

complex read 1
How to understand the result?
Does it have to be `mediumId.size == numMedia` and `mediumType.size == numMedia`?
We can add it at pattern and desc.

complex read 2
Does the result need to distinct loans about `sumLoanAmount` & `sumLoanBalance` ?

complex read 4
If there don't have a edge between `src` and `dst`, how to do it?

complex read 5
If there have more than one edge between two vertices, do we only outputs path once?

complex read 6
The pattern is contain 3 `transfer`, but the desc is more than 3 `transfer`.
Maybe we need to choose one.

complex read 8
Does `upstream` means vertex or edge or edge's amount?
The `upstream` of pattern is different from desc.

complex read 9
The params is missing `Account.id`.

complex read 10
The params is missing `startTime` & `endTime`.

complex read 11
How to compute the `finalShare`?

complex read 13
The desc is return companies and the sum of their transfer, but the pattern and result is `sumEdge2Amount`.
Maybe we need to add `Company.id` or `Compnay.name` at result.

About Sort:
It will be easier to understand if we add `descending order` at describe when it query need sort.

**Comment by qishipengqsp** [comment]
> In the implementation phase:
> 
> complex read 1 How to understand the result? Does it have to be `mediumId.size == numMedia` and `mediumType.size == numMedia`? We can add it at pattern and desc.
> 
Will remove the numMedia since it's weird to return it with the list.

> complex read 2 Does the result need to distinct loans about `sumLoanAmount` & `sumLoanBalance` ?
> 
Yes. Will specify it in the desc.

> complex read 4 If there don't have a edge between `src` and `dst`, how to do it?
> 
Return all -1. Will revise the description.

> complex read 5 If there have more than one edge between two vertices, do we only outputs path once?
> 
You are right. I add a note in this description.
TODO: Considering the case that there is a cycle encountered in graph traversal:
- Note there is no cycle in the data
- Specify how to handle this case

> complex read 6 The pattern is contain 3 `transfer`, but the desc is more than 3 `transfer`. Maybe we need to choose one.
> 
TODO: Will add a group of dots.

> complex read 8 Does `upstream` means vertex or edge or edge's amount? The `upstream` of pattern is different from desc.
> 
TODO: will explain upstream
- cycle?


> complex read 9 The params is missing `Account.id`.
> 
Will fix it.

> complex read 10 The params is missing `startTime` & `endTime`.
> 
Will fix it.

> complex read 11 How to compute the `finalShare`?
> 
TODO: will explain final share

> complex read 13 The desc is return companies and the sum of their transfer, but the pattern and result is `sumEdge2Amount`. Maybe we need to add `Company.id` or `Compnay.name` at result.
> 
TODO: groupby compared with SNB

> About Sort: It will be easier to understand if we add `descending order` at describe when it query need sort.

TODO: add one more row to describe the order of returned result.

**Comment by qishipengqsp** [comment]
Remaing TBD:

> In the implementation phase:

> complex read 6 The pattern is contain 3 `transfer`, but the desc is more than 3 `transfer`. Maybe we need to choose one.
> 
The diagram uses dots to express more than 3 accounts. TBD

> complex read 8 Does `upstream` means vertex or edge or edge's amount? The `upstream` of pattern is different from desc.
> 
TBD

> complex read 11 How to compute the `finalShare`?
> 
TBD

> complex read 13 The desc is return companies and the sum of their transfer, but the pattern and result is `sumEdge2Amount`. Maybe we need to add `Company.id` or `Compnay.name` at result.
> 
Related with GroupBy. TBD

> About Sort: It will be easier to understand if we add `descending order` at describe when it query need sort.

? TBD.

**Comment by qishipengqsp** [comment]
The remaining TODOs are moved to #50
