### ISSUE TITLE
Write have some question

### ISSUE THREAD

**Issue by BingTong0** [ldbc/ldbc_finbench_docs#54]
In the implementation phase:

Write 4
Is the `type` useful in the pattern? 

Write 8
What does the `one-off` means?

Write 9
Maybe the desc and params should be `deposit`, not `repay`, but it will be the same as Write 8.

Write 11
The person vertex don't have a property of `isBlock`.

**Comment by qishipengqsp** [comment]
> In the implementation phase:
> 
> Write 4 Is the `type` useful in the pattern?
> 
The type card is to make the expression more realistic as  `Withdraw`. However, we can review it after the suite is developed when we are trying to enrich the description.
> Write 8 What does the `one-off` means?
> 
Here  `one-off` means there is only one deposit from the loan. Can also be noted as `one-time`.
> Write 9 Maybe the desc and params should be `deposit`, not `repay`, but it will be the same as Write 8.
> 
The diagram is wrong.
> Write 11 The person vertex don't have a property of `isBlock`.

Fixed already.

**Comment by BingTong0** [comment]
@qishipengqsp 
Write9: 
The schema don't have `repay` edge type.
