### ISSUE TITLE
ReadWrite have some question

### ISSUE THREAD

**Issue by BingTong0** [ldbc/ldbc_finbench_docs#55]
Read Write 1
Does the edge1 contain the historical one?
There doesn't provide attributes for transfer edge at params.

Read Write 2
It would be better if it add desc about `fast-in and fast-out`, though we can know it at ComplexRead7.
There doesn't provide attributes at params.

Read Write 3
The person vertex don't have a property of `isBlock`. 
There doesn't provide attributes at params.

**Comment by qishipengqsp** [comment]
> Read Write 1 Does the edge1 contain the historical one? There doesn't provide attributes for transfer edge at params.
>
- There is supposed to be no historical one. In another word, the cycle is newly formed.
- Will add the properties at params.
> Read Write 2 It would be better if it add desc about `fast-in and fast-out`, though we can know it at ComplexRead7. There doesn't provide attributes at params.
> 
- Will add the desc. 
- Will add the properties at params.
> Read Write 3 The person vertex don't have a property of `isBlock`. There doesn't provide attributes at params.
- Will add the property
- Will add the properties at params.
