### ISSUE TITLE
Simple Read

### ISSUE THREAD

**Issue by BingTong0** [ldbc/ldbc_finbench_docs#57]
simple read 1: 
The desc is `account or person`, I think `person` should be removed.
The `type` of result also should be removed.

simple read2:
The query only input one `account` vertex. It would be better if change `id1` to `id`.
The pattern contains `COUNT(edge1)`, but result doesn't contain `numEdge1`. It's better to be consistent.

simple read3:
It's better to have precision about  `blockRatio`.

simple read6:
The type of result could be `ID` rather than `[ID]`.

simple read7:
Same as read6. The type of result could be `ID` rather than `[ID]`.

**Comment by qishipengqsp** [comment]
> simple read 1: The desc is `account or person`, I think `person` should be removed. The `type` of result also should be removed.
> 
The type of the result is the type of the account.

> simple read2: The query only input one `account` vertex. It would be better if change `id1` to `id`. The pattern contains `COUNT(edge1)`, but result doesn't contain `numEdge1`. It's better to be consistent.
> 
Done

> simple read3: It's better to have precision about `blockRatio`.
> 
Done

> simple read6: The type of result could be `ID` rather than `[ID]`.
> 
Done
> simple read7: Same as read6. The type of result could be `ID` rather than `[ID]`.

Done
