### ISSUE TITLE
TCR 3 Mapping does not work in the query card

### ISSUE THREAD

**Issue by qishipengqsp** [ldbc/ldbc_finbench_docs#64]
https://github.com/ldbc/ldbc_finbench_docs/pull/63

**Comment by qishipengqsp** [comment]
Spent a bit of time and did not figure it out yet.

**Comment by qishipengqsp** [comment]
<img width="825" alt="Screenshot 2023-04-26 at 15 34 10" src="https://user-images.githubusercontent.com/7361726/234502958-609e656e-88af-4b0d-9071-477f7af98e57.png">

**Comment by szarnyasg** [comment]
I think this happens due to a counter variable that's not reset when it should be. I will fix it in a moment.
