### ISSUE TITLE
Update the format, description, pattern of the query

### ISSUE THREAD

**Issue by BingTong0** [ldbc/ldbc_finbench_docs#75]
Pattern
multiple edges use dotted line & single edges use full line

Complex 5
When describing the path between two vertices, multiple edges that represent the same connection should be counted as a single edge.

Complex 8
Modify "upstream" to aggregate all incoming edges within three hops.

Complex 9
remove params about lowerbound & upperbound

Simple 5
add sort

Simple 7&8
delete 

Read Write 1&2
amt -> amount

**Comment by qishipengqsp** [comment]
fixed by @BingTong0
